# fly.toml app configuration file generated for ch-landgorila-express on 2024-12-23T05:12:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ch-landgorila-express'
primary_region = 'scl'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256MB'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
